"""add chapter_tree_snapshot table

Revision ID: 1b9047b7f088
Revises: 9f4fce4d7247
Create Date: 2026-04-05 16:33:10.648543

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1b9047b7f088"
down_revision: Union[str, Sequence[str], None] = "9f4fce4d7247"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chapter_tree_snapshots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("textbook_id", sa.Integer(), nullable=False),
        sa.Column(
            "snapshot_data",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=False,
            comment="章节树快照数据，包含所有章节的 {id, order_index, parent_id}",
        ),
        sa.Column(
            "operation_type",
            sa.String(length=50),
            nullable=False,
            comment="操作类型，如 sort, zip_import",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            comment="快照是否有效，撤回后设为 False",
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["textbook_id"], ["textbooks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_chapter_tree_snapshots_textbook_created",
        "chapter_tree_snapshots",
        ["textbook_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chapter_tree_snapshots_textbook_id"),
        "chapter_tree_snapshots",
        ["textbook_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_chapter_tree_snapshots_textbook_id"),
        table_name="chapter_tree_snapshots",
    )
    op.drop_index(
        "ix_chapter_tree_snapshots_textbook_created",
        table_name="chapter_tree_snapshots",
    )
    op.drop_table("chapter_tree_snapshots")
    # ### end Alembic commands ###
