"""add must_change_password to user

Revision ID: 9f4fce4d7247
Revises: 62c24f8a91a2
Create Date: 2026-04-02 12:16:16.622779

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9f4fce4d7247"
down_revision: Union[str, Sequence[str], None] = "62c24f8a91a2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 使用 IF EXISTS 避免 fresh DB 上报错
    op.execute("DROP INDEX IF EXISTS idx_content_search_doc_id")
    op.execute("DROP INDEX IF EXISTS idx_content_search_textbook_id")
    op.execute("DROP INDEX IF EXISTS idx_content_search_vector")
    op.execute("DROP TABLE IF EXISTS content_search_idx")
    # Add column as nullable first
    op.add_column(
        "users", sa.Column("must_change_password", sa.Boolean(), nullable=True)
    )
    # Set default value for existing rows
    op.execute(
        "UPDATE users SET must_change_password = FALSE WHERE must_change_password IS NULL"
    )
    # Make column NOT NULL
    op.alter_column("users", "must_change_password", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "must_change_password")
    op.create_table(
        "content_search_idx",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("doc_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "doc_type", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column("title", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("content", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("textbook_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("textbook_title", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "search_vector", postgresql.TSVECTOR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("content_search_idx_pkey")),
    )
    op.create_index(
        op.f("idx_content_search_vector"),
        "content_search_idx",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("idx_content_search_textbook_id"),
        "content_search_idx",
        ["textbook_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_content_search_doc_id"),
        "content_search_idx",
        ["doc_id", "doc_type"],
        unique=False,
    )
    # ### end Alembic commands ###
